{{- if .Values.gremlin.client.certCreateSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gremlin.client.secretName }}
  labels:
    app.kubernetes.io/name: {{ include "gremlin.name" . }}
    helm.sh/chart: {{ include "gremlin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: v1
type: kubernetes.io/Opaque
data:
  gremlin.cert: {{ required "A valid .Values.gremlin.client.certContent entry required!" .Values.gremlin.client.certContent | toString | b64enc }}
  gremlin.key: {{ required "A valid .Values.gremlin.client.keyContent entry required!" .Values.gremlin.client.keyContent | toString | b64enc }}
{{- end }}
