name: gremlin
version: 0.1.8
description: The Gremlin Inc client application
appVersion: "2.12.21"
apiVersion: v1
home: https://www.gremlin.com
maintainers:
- name: Sean "thor" Swehla
  email: thor@gremlin.com
- name: Philip Gebhardt
  email: phil@gremlin.com
