# Default values for gremlin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gremlin/gremlin
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

gremlin:
  teamID: ""
  hostPID: false
  hostNetwork: false
  client:
    secretName: gremlin-team-cert
    cert: file:///var/lib/gremlin/cert/gremlin.cert
    key: file:///var/lib/gremlin/cert/gremlin.key
